#!/usr/bin/env node
// Build src/patterns/tirazainArchive.ts from resources/tirazain/.
//
// Reads `resources/tirazain/manifest.json`, parses each `<slug>/pattern.oxs`,
// attaches source attribution from the manifest, and writes a TypeScript
// module the app loads at startup.
//
// Run:  npm run import-tirazain
//
// Adding new patterns is a manual step (see resources/tirazain/README.md).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DOMParser } from 'linkedom';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ARCHIVE_DIR = join(ROOT, 'resources', 'tirazain');
const MANIFEST_PATH = join(ARCHIVE_DIR, 'manifest.json');
const OUT_TS_PATH = join(ROOT, 'src', 'patterns', 'tirazainArchive.ts');
const OUT_JSON_PATH = join(ROOT, 'src', 'patterns', 'tirazainArchive.json');

// Provide DOMParser to the OXS parser (which is written for the browser).
globalThis.DOMParser = DOMParser;

// We import the existing parser dynamically so a single source of truth
// handles OXS parsing both at import time and in the running app.
const { parseOxs } = await import(join(ROOT, 'src', 'oxs', 'parseOxs.ts'));

const manifestRaw = readFileSync(MANIFEST_PATH, 'utf8');
let manifest;
try {
  manifest = JSON.parse(manifestRaw);
} catch (err) {
  console.error(`Manifest is not valid JSON: ${err.message}`);
  process.exit(1);
}
if (!Array.isArray(manifest)) {
  console.error('Manifest must be a JSON array of pattern entries.');
  process.exit(1);
}

const entries = [];
const skipped = [];

for (const m of manifest) {
  if (!m.slug || !m.url || !m.name) {
    console.warn(`Skipping entry with missing slug/url/name: ${JSON.stringify(m)}`);
    skipped.push({ entry: m, reason: 'missing slug/url/name' });
    continue;
  }
  const oxsPath = join(ARCHIVE_DIR, m.slug, 'pattern.oxs');
  if (!existsSync(oxsPath)) {
    console.warn(`No pattern.oxs in ${m.slug}/, skipping.`);
    skipped.push({ entry: m, reason: 'pattern.oxs missing' });
    continue;
  }
  let parsed;
  try {
    const xml = readFileSync(oxsPath, 'utf8');
    parsed = parseOxs(xml, m.name);
  } catch (err) {
    console.warn(`Failed to parse ${m.slug}/pattern.oxs: ${err.message}`);
    skipped.push({ entry: m, reason: `parse error: ${err.message}` });
    continue;
  }

  const pattern = {
    ...parsed.pattern,
    name: m.name,
    source: {
      archive: 'tirazain.com',
      url: m.url,
      ...(m.name ? { originalName: m.name } : {}),
      ...(m.arabicName ? { arabicName: m.arabicName } : {}),
      ...(m.region ? { region: m.region } : {}),
      ...(m.attribution ? { attribution: m.attribution } : {}),
    },
  };

  entries.push({ slug: m.slug, pattern });
}

// Emit the data as JSON (small parse cost, no TS-server churn) plus a thin
// TypeScript wrapper that imports it. Keeping data in JSON instead of as a
// large TS literal avoids the IDE lag from typechecking 10000+ lines of
// pattern data on every save.
const data = Object.fromEntries(entries.map((e) => [e.slug, e.pattern]));
writeFileSync(OUT_JSON_PATH, JSON.stringify(data, null, 0) + '\n', 'utf8');

const wrapper = `// Auto-generated by scripts/import_tirazain.mjs. Do not edit by hand.
//
// Patterns imported from the Tirazain Archive (https://tirazain.com/archive/).
// Each entry preserves the original source URL and metadata so users can
// trace any pattern back to its origin.
//
// The data lives in tirazainArchive.json — this module only re-exports it
// with a typed shape. Keeps the TS server from having to parse a giant
// literal on every save.
//
// To regenerate after adding new patterns, run:  npm run import-tirazain

import type { Pattern } from '../engine/types';
import data from './tirazainArchive.json';

export const TIRAZAIN_ARCHIVE = data as unknown as Record<string, Pattern>;
`;
writeFileSync(OUT_TS_PATH, wrapper, 'utf8');

console.log(`Wrote ${OUT_JSON_PATH}`);
console.log(`Wrote ${OUT_TS_PATH}`);
console.log(`  ${entries.length} pattern${entries.length === 1 ? '' : 's'} imported`);
if (skipped.length > 0) {
  console.log(`  ${skipped.length} skipped`);
}
