// Auto-generated by scripts/import_tirazain.mjs. Do not edit by hand.
//
// Patterns imported from the Tirazain Archive (https://tirazain.com/archive/).
// Each entry preserves the original source URL and metadata so users can
// trace any pattern back to its origin.
//
// The data lives in tirazainArchive.json — this module only re-exports it
// with a typed shape. Keeps the TS server from having to parse a giant
// literal on every save.
//
// To regenerate after adding new patterns, run:  npm run import-tirazain

import type { Pattern } from '../engine/types';
import data from './tirazainArchive.json';

export const TIRAZAIN_ARCHIVE = data as unknown as Record<string, Pattern>;
